#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Dec 10 22:33:56 2019

@author: JonPetter
"""

inputFile = open("../resources/Day2-Input.txt","r").read()

program = list(map(int, inputFile.split(",")))

debug = False
if debug: print(program)


# TODO:
    # Add real unit testing
    # refactor and clean up:
        # move intcode to separate class, maybe as static function
        # make the current script the main script
        # make printing of all calculations optional
        # rename according to convention in Day2 part 2
    # Add
    

def intcode(program, debug = False):
    """Return a intcode program that has been executed """
    print('\nINTCODE IS RUNNING...\n', 40*'-')
    
    if debug: print(program)
    
    #For each chunk, execute the opCodes
    for i in range(0,len(program),4):
        tempList = program[i:i+4]
        if debug: print('\n', tempList)
        opcode = tempList[0]
        if debug: print('Intcode: ', opcode)
        pos1, pos2, pos3 = tempList[1], tempList[2], tempList[3]

        if opcode == 99:
            if debug: print('Code 99: halting program: ', tempList)
            break
        elif opcode == 1:
            #add
            if debug: print('add :', program[pos1], 'with: ', program[pos2], 'and put in place: ', pos3)
            thesum = program[pos1] + program[pos2]
            if debug: print('sum: ', thesum)
            program[pos3] = thesum
            #print(tempList)
        elif opcode == 2:
            #multiply
            if debug: print('multiply :', program[pos1], 'with: ', program[pos2], 'and put in place: ', pos3)
            prod = program[pos1] * program[pos2]
            if debug: print('product: ', prod)
            program[pos3] = prod
        else:
            #unknown opcode, something went wrong
            print('FOUND WRONG INTCODE: ', opcode)
    
    return program
    
#To do this, before running the program, replace position 1 with the value 12 and replace position 2 with the value 2.
program[1] = 12
program[2] = 2
program = intcode(program, debug)
if debug: print(program)
print("Result Day 2-1: ", program[0])
correctAnswer = 4484226

#"Unit testing":
#intcode([1,0,0,0,99])
#intcode([2,3,0,3,99])
#intcode([2,4,4,5,99,0])
#intcode([1,1,1,4,99,5,6,0,99])
#intcode([1,9,10,3,2,3,11,0,99,30,40,50])