#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Dec 12 23:49:05 2019

@author: JonPetter
"""

OK = [False] * 4
print(OK)
counter = 0

#Check range
#Criterion 1 is always fulfilled, number is within the range given
OK[0] = True

print('OK initielt: ', OK)
#for i in range(145852, 616942):
for i in range(145852, 616942):
#    print(i)
    #Criterion 2: 6 digits
    if len(str(i)) == 6: OK[1] = True
    #Criterion 3 and 4
    istr = str(i)
    OK[3] = True
    for k in range(0,len(istr)-1):
        pair = istr[k:k+2]
        #Criterion 3: Always at least one pair
        if pair[0] == pair[1]: OK[2] = True
        #Criterion 4: Never decreasing integer value
        if pair[0] > pair[1]: OK[3] = False
    if all(OK): counter += 1
    
    OK[1:] = [False] * 3
    
print('Number of valid possible different passwords in range:', counter)